# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f677aecb07e499d71c80425d593fb721f6f1993d2aad9039a40bcb6f78ace2672da646b11813b455da1a90ad10bb663500d34ae2df25f70e22a29f9941227a7

test:
  secret_key_base: f36b603492ebb8eceea286ea898955e713c2d3fbc10637350a82e93fac05778e38c5a8600983a003e15d6485430ed5fb486da44eeb15521eeb0df46e7a307d15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
